spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/packtdb"
    username: "packt"
    password: "superSecret"

server:
  port: 9090

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}

